### ISSUE TITLE
deleteが扱えない

### ISSUE THREAD

**Issue by m-star18** [Akirakong/saves#1]
こちらのパッケージを利用させて頂いてるのですが, delete関数が扱えませんでした.
Sampleのプログラムでも実行したのですが, Errorが出てしまったので確認していただきたいです.

実行環境
Arch Linux
Python 3.9

ソースコード
```python3
import saves

num = 99
s = saves.Saves()
s.save('numer',num)
s.delete('numer')
```

実行結果
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/var/lib/snapd/snap/pycharm-professional/242/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/var/lib/snapd/snap/pycharm-professional/242/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/m-star18/.config/JetBrains/PyCharm2021.1/scratches/scratch_1.py", line 6, in <module>
    s.delete('numer')
  File "/home/m-star18/.local/lib/python3.9/site-packages/saves/saves.py", line 46, in delete
    self.__delete(key)
  File "/home/m-star18/.local/lib/python3.9/site-packages/saves/saves.py", line 119, in __delete
    self.__c.execute(sql)
sqlite3.OperationalError: no such column: numer
```

**Comment by Akirakong** [comment]
確認が遅くなりすみません。
内容確認して対応しますので少々お待ちください🙇‍♂️

**Comment by m-star18** [comment]
よろしくお願いします🤲

**Comment by Akirakong** [comment]
@m-star18 さん

 対応完了しました😄

こちらのコマンドでライブラリを更新いただくと事象が出なくなります。
`pip install saves==0.1`

対応詳細
deleteメソッド内で呼び出しているsql文のwhere句にダブルクォーテーションを追加しました。

**Comment by m-star18** [comment]
迅速な対応ありがとうございました！
とても助かりました！
無事解決したので, Closeさせていただきます.
